"""Generate exact NSIS removal commands for a packaged application tree."""

import argparse
from pathlib import Path


def _nsis_path(path: Path) -> str:
    """Return a relative Windows path safely embedded in an NSIS string."""
    value = str(path).replace("/", "\\")
    if "\r" in value or "\n" in value:
        raise ValueError("Payload paths must not contain line breaks")
    return value.replace("$", "$$").replace('"', '$\\"')


def build_uninstall_include(application_directory: Path) -> str:
    """Return deterministic commands that remove only packaged payload paths."""
    application_directory = application_directory.resolve(strict=True)
    if not application_directory.is_dir():
        raise ValueError("The application payload must be a directory")

    files = sorted(
        (
            path.relative_to(application_directory)
            for path in application_directory.rglob("*")
            if path.is_file()
        ),
        key=lambda path: str(path).casefold(),
    )
    directories = sorted(
        (
            path.relative_to(application_directory)
            for path in application_directory.rglob("*")
            if path.is_dir()
        ),
        key=lambda path: (-len(path.parts), str(path).casefold()),
    )
    if not files:
        raise ValueError("The application payload contains no files")

    lines = [
        "; Generated by tools/build_nsis_uninstall_include.py.",
        "; Delete only files and then directories supplied by this build.",
    ]
    lines.extend(f'Delete "$INSTDIR\\{_nsis_path(path)}"' for path in files)
    lines.extend(f'RMDir "$INSTDIR\\{_nsis_path(path)}"' for path in directories)
    return "\n".join(lines) + "\n"


def main() -> int:
    """Generate the include at the path requested by the build script."""
    parser = argparse.ArgumentParser()
    parser.add_argument("application_directory", type=Path)
    parser.add_argument("output_file", type=Path)
    options = parser.parse_args()
    content = build_uninstall_include(options.application_directory)
    options.output_file.parent.mkdir(parents=True, exist_ok=True)
    options.output_file.write_text(content, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
